skip-check:
  # Issue: The build output cannot be affected by user parameters other than the build entry point and the top-level source location. GitHub Actions workflow_dispatch inputs MUST be empty
  # Exclusion: We have options to filter builds on workflows
  - CKV_GHA_7
  # Issue: Ensure Terraform module sources use a commit hash
  # Exclusion: checkov not detecting we are using versions in the source URL
  - CKV_TF_1
  - CKV_TF_2
  # Issue: Ensure that the global security field has rules defined 
  # Exclusion: Security is handled by policy
  - CKV_OPENAPI_4