FROM opencoconut/ffmpeg

WORKDIR /app

ARG application="audiostream1"

# Create Script
RUN touch ffmpeg-script.sh
RUN echo "application=\"$application\"" >> ffmpeg-script.sh
RUN echo "source=\$(printenv source)" >> ffmpeg-script.sh
RUN echo "ffmpeg_url=\"rtmps://\${source}:443/\${application}\" " >> ffmpeg-script.sh
RUN echo "ffmpeg -re -i \$audioFilePath -c copy -f flv \"\${ffmpeg_url} flashver=FMLE/3.0\20(compatible;\20FMSc/1.0) live=true pubUser=wowza playpath=\$fileName\" -loglevel verbose" >> ffmpeg-script.sh